### PR TITLE
10 upgrade mvc project

### PR DESCRIPTION
**Pull request by sswietoniowski**
Implemented (#10).

### CODE REVIEW

**Review by sswietoniowski — COMMENTED** [review]
Accepted it looks OK :-)

**Review by sswietoniowski-codecool — APPROVED** [review]
Accepted, it looks OK :-).

**Review by sswietoniowski-codecool — APPROVED** [review]
It looks OK :-)

**Review by sswietoniowski-codecool — APPROVED** [review]
Done :-)

**Pull request merged**
